feat: add --config option for custom .grmc(.js) path
graphile/migrate pull request #103
Opened 2021-02-24 16:24 UTC by ben-pr-p

## Description

Solution for https://github.com/graphile/migrate/issues/102.

## Performance impact

Neglible.

## Security impact

Unknown

## Checklist

- [x] My code matches the project's code style and `yarn lint:fix` passes.
- [x] I've added tests for the new feature, and `yarn test` passes.
- [x] I have detailed the new feature in the relevant documentation.
- [ ] I have added this feature to 'Pending' in the `RELEASE_NOTES.md` file (if one exists).
- [ ] If this is a breaking change I've explained why.

2021-03-16 15:06 UTC, benjie requested changes
Thanks for your work on this, Ben - I think letting users customise where their config file is sourced from is a good idea. I've requested a few changes:

2021-03-16 15:06 UTC, benjie commented on src/commands/_common.ts
> +export type ConfigOptions = { config: string };
I think this should be optional?
```suggestion
export type ConfigOptions = { config?: string };
```

2021-03-16 15:06 UTC, benjie commented on README.md
> +  --config Optional path to .gmrc(.js) - default is `${pwd}.gmrc`      [string]
It looks like you updated all of these manually (because the alignment is off); instead, you can use the `scripts/update-docs.js` script.

2021-03-16 15:07 UTC, benjie commented
And sorry it's taken me so long to get around to reviewing this... I've been working on something else :grin:

2021-03-17 17:49 UTC, ben-pr-p commented
Should be all good to go!

2021-04-16 10:47 UTC, closed without merging

2021-04-16 16:10 UTC, benjie commented
Thanks @ben-pr-p :raised_hands: This is out in v1.1.0 (`graphile-migrate@next`)