Ensure connection strings are distinct
graphile/migrate pull request #91
Opened 2020-09-10 00:26 UTC by richchurcher

As discussed in Discord, this:
- [x] checks `connectionString !== shadowConnectionString`
- [x] checks `connectionString !== rootConnectionString`
- [x] adds some simple instructions for getting the tests to pass in a container

I thought it was probably safe to leave `rootConnectionString !== shadowConnectionString` up to the user's brain :slightly_smiling_face:

2020-09-10 00:28 UTC, richchurcher commented
I seem to have picked up the docs change from my other PR here, oops.

2020-09-15 12:11 UTC, benjie requested changes
Please run

```
git checkout main CONTRIBUTING.md README.md
```

then commit and push the result. No need to rewrite history, we squash-merge.

A separate PR containing the CONTRIBUTING.md file would be welcome.

2020-09-15 12:11 UTC, benjie commented
(The deliberate changes in this PR look fine to me - thanks!)

2020-09-15 21:05 UTC, richchurcher commented
All set, I think! Sorry for creating a bit of extra review work.

2020-09-16 08:58 UTC, benjie approved these changes
Excellent; thanks!

2020-09-16 08:58 UTC, merged